export default {};

export const fragenList = [
  // 10 preguntas
  {
    pregunta: "¿Como Pedirias unas papas fritas?",
    correct: "Ich werde Pommes haben",
    wrong: "Ich wirst Pommes haben",
    why: 'wirst se usa cuando estamos hablando en "du"',
    cost: 10,
  },
  {
    pregunta: "¿Como Pedirias una hamburguesa?",
    correct: "Ich werde Hamburger haben",
    wrong: "Ich wirst Hamburger haben",
    why: 'wirst se usa cuando estamos hablando en "du"',
    cost: 10,
  },
  {
    pregunta: "¿Como Pedirias unas alitas?",
    correct: "Kann ich 12 Hühnerflügel haben?",
    wrong: "Kann ich habe 12 Hühnerflügel?",
    why: '"habe" debe estar al final de la oracion',
    cost: 10,
  },
  {
    pregunta: "Si tendrias que ordenar una pizza ¿como lo dirias?",
    correct: "Bring mir eine Peperoni-Pizza",
    wrong: "Bring mir ein Peperoni-Pizza",
    why: 'el articulo para pizza es "die"',
    cost: 10,
  },
  {
    pregunta: "¿Como se ordena un vaso de refresco?",
    correct: "Ich werde ein Glas Soda haben",
    wrong: "Ich werde eine Glas Soda haben",
    why: 'el articulo para vazo es "das"',
    cost: 10,
  },
  {
    pregunta: "¿Como Pedirias una barra de chocolate?",
    correct: "Kann ich eine Tafel Schokolade haben?",
    wrong: "Kann ich habe eine Tafel Schokolade?",
    why: "el verbo principal debe ir al final de la oracion",
    cost: 10,
  },
  {
    pregunta: "Si tu orden de una pizza esta incorrecta ¿Como dirias que tiene un problema?",
    correct: "Entschuldigung, meine Pizza hat ein Problem",
    wrong: "Entschuldigung, meine Pizza hat eine Problem",
    why: 'El articulo de problem es "das"',
    cost: 10,
  },
  {
    pregunta: "Si tus alitas tiene un pelo ¿como le dirias al mesero?",
    correct: "Entschuldigung Meine Hühnerflügel haben Haare",
    wrong: "Entschuldigung Meine Hühnerflügel haben jare",
    why: 'La palabra para pelo en aleman es "haare"',
    cost: 10,
  },
  {
    pregunta: "¿Cual es la forma correcta de decir galletas de chispas de chocolate?",
    correct: "Schokoladenkekse",
    wrong: "Schokolade chip kekse",
    why: "La verdad no estoy seguro, pero deberia ser asi...",
    cost: 10,
  },
  {
    pregunta: "sind Spaghetti und Ramen gleich?",
    correct: "Nein",
    wrong: "Ja",
    why: "Spaghetti es una pasta italiana, ramen es una pasta china",
    cost: 10,
  },
  // 10 preguntas
  {
    pregunta: 'ist Pfannkuchen deutsch für "panqueques"?',
    correct: "Ja",
    wrong: "Nein",
    why: "Pfannkuchen si es panqueques en aleman",
    cost: 10,
  },
  {
    pregunta: "Hähnchenstreifen ist deutsch für?",
    correct: "Chicken strips",
    wrong: "Chicken fingers",
    why: "Pfannkuchen es panqueques en aleman",
    cost: 10,
  },
  {
    pregunta: '¿Cual es la palabra en aleman para "Donas"?',
    correct: "Donuts",
    wrong: "Doughnuts",
    why: "Donuts es donas en aleman",
    cost: 10,
  },
  {
    pregunta: '¿Cual es la palabra en aleman para "Dulces"?',
    correct: "Süßigkeiten",
    wrong: "Kandy",
    why: "Pfannkuchen si es panqueques en aleman",
    cost: 10,
  },
  {
    pregunta: '¿Cual es la palabra en aleman para "Chocolate"',
    correct: "Schokolade",
    wrong: "Schocolate",
    why: "Schokolade es Chocolate en aleman",
    cost: 10,
  },
  {
    pregunta: '"Kann ich bitte 2 Baleadas haben?" ¿es una oracion bien hecha?',
    correct: "Ja",
    wrong: "Nein",
    why: "Si esta bien estructurada y escrita",
    cost: 10,
  },
  {
    pregunta: 'Wofür ist das Wort "Kekse"?',
    correct: "Galletas",
    wrong: "Quequito",
    why: "En serio... tengo que explicarlo",
    cost: 10,
  },
  {
    pregunta: "Wie würden Sie einen Teller Spaghetti bestellen",
    correct: "Kann ich einen Teller Spaghetti haben?",
    wrong: "Kann ich eine Teller Spaghetti haben?",
    why: 'El articulo para teller es "der"',
    cost: 10,
  },
  {
    pregunta: '¿Cual es la palabra en aleman para "Pizza"?',
    correct: "Pizza",
    wrong: "Pißa",
    why: "Pizza es Pizza en aleman...",
    cost: 10,
  },
  {
    pregunta: "Welche der Pizza ist die teuerste",
    correct: "¿Cual es la pizza mas cara?",
    wrong: "Cual es la pizza mas tostada",
    why: 'La palabra teuerste quiere decir "mas cara"',
    cost: 10,
  },
  // 10 preguntas
];
